// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.taskmanager.domain;

import com.taskmanager.domain.TaskDetail;
import com.taskmanager.domain.TaskDetailDataOnDemand;
import com.taskmanager.domain.TaskDetailIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TaskDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TaskDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TaskDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TaskDetailIntegrationTest: @Transactional;
    
    @Autowired
    TaskDetailDataOnDemand TaskDetailIntegrationTest.dod;
    
    @Test
    public void TaskDetailIntegrationTest.testCountTaskDetails() {
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", dod.getRandomTaskDetail());
        long count = TaskDetail.countTaskDetails();
        Assert.assertTrue("Counter for 'TaskDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TaskDetailIntegrationTest.testFindTaskDetail() {
        TaskDetail obj = dod.getRandomTaskDetail();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to provide an identifier", id);
        obj = TaskDetail.findTaskDetail(id);
        Assert.assertNotNull("Find method for 'TaskDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TaskDetail' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TaskDetailIntegrationTest.testFindAllTaskDetails() {
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", dod.getRandomTaskDetail());
        long count = TaskDetail.countTaskDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'TaskDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TaskDetail> result = TaskDetail.findAllTaskDetails();
        Assert.assertNotNull("Find all method for 'TaskDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TaskDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TaskDetailIntegrationTest.testFindTaskDetailEntries() {
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", dod.getRandomTaskDetail());
        long count = TaskDetail.countTaskDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TaskDetail> result = TaskDetail.findTaskDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TaskDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TaskDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TaskDetailIntegrationTest.testFlush() {
        TaskDetail obj = dod.getRandomTaskDetail();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to provide an identifier", id);
        obj = TaskDetail.findTaskDetail(id);
        Assert.assertNotNull("Find method for 'TaskDetail' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTaskDetail(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TaskDetail' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskDetailIntegrationTest.testMergeUpdate() {
        TaskDetail obj = dod.getRandomTaskDetail();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to provide an identifier", id);
        obj = TaskDetail.findTaskDetail(id);
        boolean modified =  dod.modifyTaskDetail(obj);
        Integer currentVersion = obj.getVersion();
        TaskDetail merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TaskDetail' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskDetailIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", dod.getRandomTaskDetail());
        TaskDetail obj = dod.getNewTransientTaskDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TaskDetail' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TaskDetail' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TaskDetailIntegrationTest.testRemove() {
        TaskDetail obj = dod.getRandomTaskDetail();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TaskDetail' failed to provide an identifier", id);
        obj = TaskDetail.findTaskDetail(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TaskDetail' with identifier '" + id + "'", TaskDetail.findTaskDetail(id));
    }
    
}
