// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.taskmanager.domain;

import com.taskmanager.domain.UserDetail;
import com.taskmanager.domain.UserDetailDataOnDemand;
import com.taskmanager.domain.UserDetailIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserDetailIntegrationTest: @Transactional;
    
    @Autowired
    UserDetailDataOnDemand UserDetailIntegrationTest.dod;
    
    @Test
    public void UserDetailIntegrationTest.testCountUserDetails() {
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", dod.getRandomUserDetail());
        long count = UserDetail.countUserDetails();
        Assert.assertTrue("Counter for 'UserDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserDetailIntegrationTest.testFindUserDetail() {
        UserDetail obj = dod.getRandomUserDetail();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to provide an identifier", id);
        obj = UserDetail.findUserDetail(id);
        Assert.assertNotNull("Find method for 'UserDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserDetail' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserDetailIntegrationTest.testFindAllUserDetails() {
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", dod.getRandomUserDetail());
        long count = UserDetail.countUserDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserDetail> result = UserDetail.findAllUserDetails();
        Assert.assertNotNull("Find all method for 'UserDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserDetailIntegrationTest.testFindUserDetailEntries() {
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", dod.getRandomUserDetail());
        long count = UserDetail.countUserDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserDetail> result = UserDetail.findUserDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserDetailIntegrationTest.testFlush() {
        UserDetail obj = dod.getRandomUserDetail();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to provide an identifier", id);
        obj = UserDetail.findUserDetail(id);
        Assert.assertNotNull("Find method for 'UserDetail' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserDetail(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserDetail' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserDetailIntegrationTest.testMergeUpdate() {
        UserDetail obj = dod.getRandomUserDetail();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to provide an identifier", id);
        obj = UserDetail.findUserDetail(id);
        boolean modified =  dod.modifyUserDetail(obj);
        Integer currentVersion = obj.getVersion();
        UserDetail merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserDetail' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserDetailIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", dod.getRandomUserDetail());
        UserDetail obj = dod.getNewTransientUserDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserDetail' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserDetail' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserDetailIntegrationTest.testRemove() {
        UserDetail obj = dod.getRandomUserDetail();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserDetail' failed to provide an identifier", id);
        obj = UserDetail.findUserDetail(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserDetail' with identifier '" + id + "'", UserDetail.findUserDetail(id));
    }
    
}
